Repository thoth-station/jupyter-nbrequirements, pull requests merged in 2020-11, with the labels that each got.

#280 Adjust recommendation type and reviewers
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#284 Automatic update of dependency thamos from 1.1.1 to 1.2.0
  Pipfile.lock
Labels: approved, bot, kebechet, size/M

#286 Adjust links for release
  js/package.json
  jupyter_nbrequirements/__about__.py
Labels: size/S

#288 Automatic update of dependency invectio from 0.0.7 to 0.1.0
  Pipfile.lock
Labels: approved, bot, kebechet, size/M

#289 Automatic update of dependency thamos from 1.2.0 to 1.3.1
  Pipfile.lock
Labels: approved, bot, kebechet, size/M

#282 Introduce ADR for dependencies management in Jupyter notebooks
  docs/0000-dependencies-management-jupyter-notebooks.md
  docs/template.md
Labels: approved, size/L
