Repository thoth-station/jupyter-nbrequirements, pull requests merged in 2020-07, with the labels that each got.

#244 Automatic update of dependency ipykernel from 5.1.4 to 5.3.3
  Pipfile.lock
Labels: approved, bot, kebechet, size/XL

#245 Automatic update of dependency ipython from 7.9.0 to 7.16.1
  Pipfile.lock
Labels: approved, bot, kebechet, size/XL

#247 Automatic update of dependency thamos from 0.9.3 to 0.10.6
  Pipfile.lock
Labels: approved, bot, kebechet, size/XL

#249 Automatic update of dependency thoth-python from 0.9.1 to 0.10.0
  Pipfile.lock
Labels: approved, bot, kebechet, size/XL

#251 Automatic update of dependency flake8 from 3.7.8 to 3.8.3
  Pipfile.lock
Labels: approved, bot, kebechet, size/XS

#254 Automatic update of dependency twine from 2.0.0 to 3.2.0
  Pipfile.lock
Labels: approved, bot, kebechet, size/XS

#241 chg: doc: thoth-station is the upstream now
  README.md
Labels: approved, size/S

#261 Automatic update of dependency ipykernel from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: approved, bot, kebechet
